export const imageMimeTypes: Record<string, string[]> = {
  'image/jpeg': ['.jpeg', '.jpg', '.jpe', '.jif', '.jfif', '.jfif-tbnl', '.pjpg', '.pjpeg', '.pjp'],
  'image/pjpeg': ['.jpe', '.jpeg', '.jpg', '.pjpg', '.jfi', '.jfif', '.jfif-tbnl', '.jif'],
  'image/svg+xml': ['.svg', '.svgz'],
  'image/png': ['.png'],
  'image/apng': ['.apng', '.png'],
  'image/x-icon': ['.ico', '.cur'],
  'image/vnd.microsoft.icon': ['.ico'],
  'image/webp': ['.webp'],
  'image/avif': ['.avif'],
  'image/gif': ['.gif'],
  'image/bmp': ['.bmp'],
  'image/x-portable-bitmap': ['.pbm'],
  'image/tiff': ['.tiff', '.tif'],
  'image/vnd.adobe.photoshop': ['.psd'],
  'image/vnd.dwg': ['.dwg'],
  'image/vnd.dxf': ['.dxf'],
};

export const otherMimeTypes: Record<string, string[]> = {
  'text/csv': ['.csv'],
  'text/markdown': ['.md', '.markdown', '.mdown', '.markdn'],
  'text/plain': ['.conf', '.def', '.diff', '.in', '.ksh', '.list', '.log', '.pl', '.text', '.txt'],
  'text/richtext': ['.rtx'],
  'application/xml': ['.xml'],
  'text/xml': ['.xml'],
  'application/json': ['.json'],
  'application/msword': ['.doc', '.dot', '.wiz'],
  'application/octet-stream': [
    '.a',
    '.bin',
    '.bpk',
    '.deploy',
    '.dist',
    '.distz',
    '.dmg',
    '.dms',
    '.dump',
    '.elc',
    '.lha',
    '.lrf',
    '.lzh',
    '.o',
    '.obj',
    '.pkg',
    '.so',
  ],
  'application/pdf': ['.pdf'],
  'application/rtf': ['.rtf'],
  'application/vnd.amazon.ebook': ['.azw'],
  'application/vnd.apple.installer+xml': ['.mpkg'],
  'application/vnd.mozilla.xul+xml': ['.xul'],
  'application/vnd.ms-fontobject': ['.eot'],
  'application/vnd.oasis.opendocument.presentation': ['.odp'],
  'application/vnd.oasis.opendocument.spreadsheet': ['.ods'],
  'application/vnd.oasis.opendocument.text': ['.odt'],
  'application/vnd.openxmlformats-officedocument.presentationml.presentation': ['.pptx'],
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx'],
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['.docx'],
  'application/vnd.rar': ['.rar'],
  'application/x-rar-compressed': ['.rar'],
  'application/vnd.visio': ['.vsd', '.vss', '.vst', '.vsw', '.vsdx', '.vssx', '.vstx', '.vssm', '.vstm'],
  'application/x-7z-compressed': ['.7z'],
  'application/x-abiword': ['.abw'],
  'application/x-bzip': ['.bz'],
  'application/x-bzip2': ['.bz2'],
  'application/x-csh': ['.csh'],
  'application/x-freearc': ['.arc'],
  'application/x-sh': ['.sh'],
  'application/x-shockwave-flash': ['.swf'],
  'application/x-tar': ['.tar'],
  'application/xhtml+xml': ['.xhtml'],
  'application/zip': ['.zip'],
  'application/zip-compressed': ['.zip'],
  'application/x-zip-compressed': ['.zip'],
  'audio/aac': ['.aac', '.m4a'],
  'audio/midi': ['.mid', '.midi'],
  'audio/mpeg': ['.mp3'],
  'audio/ogg': ['.oga'],
  'audio/opus': ['.opus'],
  'audio/wav': ['.wav'],
  'audio/webm': ['.weba'],
  'audio/x-wav': ['.wav'],
  'font/otf': ['.otf'],
  'font/ttf': ['.ttf'],
  'font/woff': ['.woff'],
  'font/woff2': ['.woff2'],
  'text/calendar': ['.ics'],
  'text/css': ['.css'],
  'text/html': ['.html', '.htm'],
  'text/javascript': ['.js'],
  'video/3gpp': ['.3gp'],
  'video/3gpp2': ['.3g2'],
  'video/mp2t': ['.ts'],
  'video/mpeg': ['.mpeg'],
  'video/ogg': ['.ogv'],
  'video/webm': ['.webm'],
  'video/x-msvideo': ['.avi'],
  'application/andrew-inset': ['.ez'],
  'application/applixware': ['.aw'],
  'application/atom+xml': ['.atom'],
  'application/atomcat+xml': ['.atomcat'],
  'application/atomsvc+xml': ['.atomsvc'],
  'application/ccxml+xml': ['.ccxml'],
  'application/emma+xml': ['.emma'],
  'application/epub+zip': ['.epub'],
  'application/font-tdpfr': ['.pfr'],
  'application/gzip': ['.gz', '.tgz'],
  'application/hyperstudio': ['.stk'],
  'application/java-archive': ['.jar'],
  'application/java-serialized-object': ['.ser'],
  'application/java-vm': ['.class'],
  'application/lost+xml': ['.lostxml'],
  'application/mac-binhex40': ['.hqx'],
  'application/mac-compactpro': ['.cpt'],
  'application/marc': ['.mrc'],
  'application/mathematica': ['.ma', '.mb', '.nb'],
  'application/oda': ['.oda'],
  'application/pics-rules': ['.prf'],
  'application/pkcs10': ['.p10'],
  'application/pkcs7-mime': ['.p7c', '.p7m'],
  'application/pkcs7-signature': ['.p7s'],
  'application/vnd.cinderella': ['.cdy'],
  'application/vnd.groove-vcard': ['.vcg'],
  'application/vnd.handheld-entertainment+xml': ['.zmm'],
  'application/vnd.hbci': ['.hbci'],
  'application/vnd.hhe.lesson-player': ['.les'],
  'application/vnd.hp-hpgl': ['.hpgl'],
  'application/vnd.hp-hpid': ['.hpid'],
  'application/vnd.hp-hps': ['.hps'],
  'application/vnd.hp-jlyt': ['.jlt'],
  'application/vnd.hp-pcl': ['.pcl'],
  'application/vnd.hp-pclxl': ['.pclxl'],
  'application/vnd.hydrostatix.sof-data': ['.sfd-hdstx'],
  'application/vnd.hzn-3d-crossword': ['.x3d'],
  'application/vnd.ibm.minipay': ['.mpy'],
  'application/vnd.ibm.modcap': ['.afp', '.list3820', '.listafp'],
  'application/vnd.ibm.rights-management': ['.irm'],
  'application/vnd.ibm.secure-container': ['.sc'],
  'application/vnd.iccprofile': ['.icc', '.icm'],
  'application/vnd.igloader': ['.igl'],
  'application/vnd.immervision-ivp': ['.ivp'],
  'application/vnd.immervision-ivu': ['.ivu'],
  'application/vnd.intercon.formnet': ['.xpw', '.xpx'],
  'application/vnd.intu.qbo': ['.qbo'],
  'application/vnd.intu.qfx': ['.qfx'],
  'application/vnd.ipunplugged.rcprofile': ['.rcprofile'],
  'application/vnd.irepository.package+xml': ['.irp'],
  'application/vnd.is-xpr': ['.xpr'],
  'application/vnd.jam': ['.jam'],
  'application/vnd.jcp.javame.midlet-rms': ['.rms'],
  'application/vnd.jisp': ['.jisp'],
  'application/vnd.joost.joda-archive': ['.joda'],
  'application/vnd.kahootz': ['.ktr', '.ktz'],
  'application/vnd.kde.karbon': ['.karbon'],
  'application/vnd.kde.kchart': ['.chrt'],
  'application/vnd.kde.kformula': ['.kfo'],
  'application/vnd.kde.kivio': ['.flw'],
  'application/vnd.kde.kontour': ['.kon'],
  'application/vnd.kde.kpresenter': ['.kpr', '.kpt'],
  'application/vnd.kde.kspread': ['.ksp'],
  'application/vnd.kde.kword': ['.kwd', '.kwt'],
  'application/vnd.kenameaapp': ['.htke'],
  'application/vnd.kidspiration': ['.kia'],
  'application/vnd.kinar': ['.kne', '.knp'],
  'application/vnd.koan': ['.skd', '.skm', '.skp', '.skt'],
  'application/vnd.kodak-descriptor': ['.sse'],
  'application/vnd.llamagraphics.life-balance.desktop': ['.lbd'],
  'application/vnd.llamagraphics.life-balance.exchange+xml': ['.lbe'],
  'application/vnd.lotus-1-2-3': ['.123'],
  'application/vnd.lotus-approach': ['.apr'],
  'application/vnd.lotus-freelance': ['.pre'],
  'application/vnd.lotus-notes': ['.nsf'],
  'application/vnd.lotus-organizer': ['.org'],
  'application/vnd.lotus-screencam': ['.scm'],
  'application/vnd.lotus-wordpro': ['.lwp'],
  'application/vnd.macports.portpkg': ['.portpkg'],
  'application/vnd.mcd': ['.mcd'],
  'application/vnd.medcalcdata': ['.mc1'],
  'application/vnd.mediastation.cdkey': ['.cdkey'],
  'application/vnd.mfer': ['.mwf'],
  'application/vnd.mfmp': ['.mfm'],
  'application/vnd.micrografx.flo': ['.flo'],
  'application/vnd.micrografx.igx': ['.igx'],
  'application/vnd.mif': ['.mif'],
  'application/vnd.mobius.daf': ['.daf'],
  'application/vnd.mobius.dis': ['.dis'],
  'application/vnd.mobius.mbk': ['.mbk'],
  'application/vnd.mobius.mqy': ['.mqy'],
  'application/vnd.mobius.msl': ['.msl'],
  'application/vnd.mobius.plc': ['.plc'],
  'application/vnd.mobius.txf': ['.txf'],
  'application/vnd.mophun.application': ['.mpn'],
  'application/vnd.mophun.certificate': ['.mpc'],
  'application/vnd.ms-artgalry': ['.cil'],
  'application/vnd.ms-cab-compressed': ['.cab'],
  'application/vnd.ms-excel': ['.xla', '.xlb', '.xlc', '.xlm', '.xls', '.xlt', '.xlw'],
  'application/vnd.ms-excel.addin.macroenabled.12': ['.xlam'],
  'application/vnd.ms-excel.sheet.binary.macroenabled.12': ['.xlsb'],
  'application/vnd.ms-excel.sheet.macroenabled.12': ['.xlsm'],
  'application/vnd.ms-excel.template.macroenabled.12': ['.xltm'],
  'application/vnd.ms-htmlhelp': ['.chm'],
  'application/vnd.ms-ims': ['.ims'],
  'application/vnd.ms-lrm': ['.lrm'],
  'application/vnd.ms-pki.seccat': ['.cat'],
  'application/vnd.ms-pki.stl': ['.stl'],
  'application/vnd.ms-powerpoint': ['.pot', '.ppa', '.pps', '.ppt', '.pwz'],
  'application/vnd.ms-powerpoint.addin.macroenabled.12': ['.ppam'],
  'application/vnd.ms-powerpoint.presentation.macroenabled.12': ['.pptm'],
  'application/vnd.ms-powerpoint.slide.macroenabled.12': ['.sldm'],
  'application/vnd.ms-powerpoint.slideshow.macroenabled.12': ['.ppsm'],
  'application/vnd.ms-powerpoint.template.macroenabled.12': ['.potm'],
  'application/vnd.ms-project': ['.mpp', '.mpt'],
  'application/vnd.ms-word.document.macroenabled.12': ['.docm'],
  'application/vnd.ms-word.template.macroenabled.12': ['.dotm'],
  'application/vnd.ms-works': ['.wcm', '.wdb', '.wks', '.wps'],
  'application/vnd.ms-wpl': ['.wpl'],
  'application/vnd.ms-xpsdocument': ['.xps'],
  'application/vnd.mseq': ['.mseq'],
  'application/vnd.musician': ['.mus'],
  'application/vnd.muvee.style': ['.msty'],
  'application/cu-seeme': ['.cu'],
  'application/davmount+xml': ['.davmount'],
  'application/ecmascript': ['.ecma'],
  'application/mathml+xml': ['.mathml', '.mml'],
  'application/mbox': ['.mbox'],
  'application/mediaservercontrol+xml': ['.mscml'],
  'application/mp4': ['.mp4s'],
  'application/mxf': ['.mxf'],
  'application/oebps-package+xml': ['.opf'],
  'application/ogg': ['.ogx'],
  'application/onenote': ['.onepkg', '.onetmp', '.onetoc', '.onetoc2'],
  'application/patch-ops-error+xml': ['.xer'],
  'application/pgp-encrypted': ['.pgp'],
  'application/pgp-signature': ['.asc', '.sig'],
  'application/pkix-cert': ['.cer'],
  'application/pkix-crl': ['.crl'],
  'application/pkix-pkipath': ['.pkipath'],
  'application/pkixcmp': ['.pki'],
  'application/pls+xml': ['.pls'],
  'application/postscript': ['.ai', '.eps', '.ps'],
  'application/prql': ['.prql'],
  'application/prs.cww': ['.cww'],
  'application/rdf+xml': ['.rdf'],
  'application/reginfo+xml': ['.rif'],
  'application/relax-ng-compact-syntax': ['.rnc'],
  'application/resource-lists+xml': ['.rl'],
  'application/resource-lists-diff+xml': ['.rld'],
  'application/rls-services+xml': ['.rs'],
  'application/rsd+xml': ['.rsd'],
  'application/rss+xml': ['.rss', '.xml'],
  'application/sbml+xml': ['.sbml'],
  'application/scvp-cv-request': ['.scq'],
  'application/scvp-cv-response': ['.scs'],
  'application/scvp-vp-request': ['.spq'],
  'application/scvp-vp-response': ['.spp'],
  'application/sdp': ['.sdp'],
  'application/set-payment-initiation': ['.setpay'],
  'application/set-registration-initiation': ['.setreg'],
  'application/shf+xml': ['.shf'],
  'application/smil+xml': ['.smi', '.smil'],
  'application/sparql-query': ['.rq'],
  'application/sparql-results+xml': ['.srx'],
  'application/srgs': ['.gram'],
  'application/srgs+xml': ['.grxml'],
  'application/ssml+xml': ['.ssml'],
  'application/vnd.3gpp.pic-bw-large': ['.plb'],
  'application/vnd.3gpp.pic-bw-small': ['.psb'],
  'application/vnd.3gpp.pic-bw-var': ['.pvb'],
  'application/vnd.3gpp2.tcap': ['.tcap'],
  'application/vnd.3m.post-it-notes': ['.pwn'],
  'application/vnd.accpac.simply.aso': ['.aso'],
  'application/vnd.accpac.simply.imp': ['.imp'],
  'application/vnd.acucobol': ['.acu'],
  'application/vnd.acucorp': ['.acutc', '.atc'],
  'application/vnd.adobe.air-application-installer-package+zip': ['.air'],
  'application/vnd.adobe.xdp+xml': ['.xdp'],
  'application/vnd.adobe.xfdf': ['.xfdf'],
  'application/vnd.airzip.filesecure.azf': ['.azf'],
  'application/vnd.airzip.filesecure.azs': ['.azs'],
  'application/vnd.americandynamics.acc': ['.acc'],
  'application/vnd.amiga.ami': ['.ami'],
  'application/vnd.android.package-archive': ['.apk'],
  'application/vnd.anser-web-certificate-issue-initiation': ['.cii'],
  'application/vnd.anser-web-funds-transfer-initiation': ['.fti'],
  'application/vnd.antix.game-component': ['.atx'],
  'application/vnd.arastra.swi': ['.swi'],
  'application/vnd.audiograph': ['.aep'],
  'application/vnd.blueice.multipass': ['.mpm'],
  'application/vnd.bmi': ['.bmi'],
  'application/vnd.businessobjects': ['.rep'],
  'application/vnd.chemdraw+xml': ['.cdxml'],
  'application/vnd.chipnuts.karaoke-mmd': ['.mmd'],
  'application/vnd.claymore': ['.cla'],
  'application/vnd.clonk.c4group': ['.c4d', '.c4f', '.c4g', '.c4p', '.c4u'],
  'application/vnd.commonspace': ['.csp'],
  'application/vnd.contact.cmsg': ['.cdbcmsg'],
  'application/vnd.cosmocaller': ['.cmc'],
  'application/vnd.crick.clicker': ['.clkx'],
  'application/vnd.crick.clicker.keyboard': ['.clkk'],
  'application/vnd.crick.clicker.palette': ['.clkp'],
  'application/vnd.crick.clicker.template': ['.clkt'],
  'application/vnd.crick.clicker.wordbank': ['.clkw'],
  'application/vnd.criticaltools.wbs+xml': ['.wbs'],
  'application/vnd.ctc-posml': ['.pml'],
  'application/vnd.cups-ppd': ['.ppd'],
  'application/vnd.curl.car': ['.car'],
  'application/vnd.curl.pcurl': ['.pcurl'],
  'application/vnd.data-vision.rdz': ['.rdz'],
  'application/vnd.debian.binary-package': ['.deb', '.udeb'],
  'application/vnd.denovo.fcselayout-link': ['.fe_launch'],
  'application/vnd.dna': ['.dna'],
  'application/vnd.dolby.mlp': ['.mlp'],
  'application/vnd.dpgraph': ['.dpg'],
  'application/vnd.dreamfactory': ['.dfac'],
  'application/vnd.dynageo': ['.geo'],
  'application/vnd.ecowin.chart': ['.mag'],
  'application/vnd.enliven': ['.nml'],
  'application/vnd.epson.esf': ['.esf'],
  'application/vnd.epson.msf': ['.msf'],
  'application/vnd.epson.quickanime': ['.qam'],
  'application/vnd.epson.salt': ['.slt'],
  'application/vnd.epson.ssf': ['.ssf'],
  'application/vnd.eszigno3+xml': ['.es3', '.et3'],
  'application/vnd.ezpix-album': ['.ez2'],
  'application/vnd.ezpix-package': ['.ez3'],
  'application/vnd.fdf': ['.fdf'],
  'application/vnd.fdsn.mseed': ['.mseed'],
  'application/vnd.fdsn.seed': ['.dataless', '.seed'],
  'application/vnd.flographit': ['.gph'],
  'application/vnd.fluxtime.clip': ['.ftc'],
  'application/vnd.framemaker': ['.book', '.fm', '.frame', '.maker'],
  'application/vnd.frogans.fnc': ['.fnc'],
  'application/vnd.frogans.ltf': ['.ltf'],
  'application/vnd.fsc.weblaunch': ['.fsc'],
  'application/vnd.fujitsu.oasys': ['.oas'],
  'application/vnd.fujitsu.oasys2': ['.oa2'],
  'application/vnd.fujitsu.oasys3': ['.oa3'],
  'application/vnd.fujitsu.oasysgp': ['.fg5'],
  'application/vnd.fujitsu.oasysprs': ['.bh2'],
  'application/vnd.fujixerox.ddd': ['.ddd'],
  'application/vnd.fujixerox.docuworks': ['.xdw'],
  'application/vnd.fujixerox.docuworks.binder': ['.xbd'],
  'application/vnd.fuzzysheet': ['.fzs'],
  'application/vnd.genomatix.tuxedo': ['.txd'],
  'application/vnd.geogebra.file': ['.ggb'],
  'application/vnd.geogebra.tool': ['.ggt'],
  'application/vnd.geometry-explorer': ['.gex', '.gre'],
  'application/vnd.gerber': ['.gbr'],
  'application/vnd.gmx': ['.gmx'],
  'application/vnd.google-earth.kml+xml': ['.kml'],
  'application/vnd.google-earth.kmz': ['.kmz'],
  'application/vnd.grafeq': ['.gqf', '.gqs'],
  'application/vnd.groove-account': ['.gac'],
  'application/vnd.groove-help': ['.ghf'],
  'application/vnd.groove-identity-message': ['.gim'],
  'application/vnd.groove-injector': ['.grv'],
  'application/vnd.groove-tool-message': ['.gtm'],
  'application/vnd.groove-tool-template': ['.tpl'],
  'application/yaml': ['.yaml', '.yml'],
};
